---

name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          level: warning
  build-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-1.18.x-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-1.18.x
      - run: |
          rm -rf ./dist
          go build -buildmode=plugin -o ./dist/pkgboundaries.so ./plugin
      - name: install golangci-lint
        run: |
          curl -o golangci-lint.tar.gz -sL https://github.com/golangci/golangci-lint/releases/download/v${GOLANGCI_LINT_VERSION}/golangci-lint-${GOLANGCI_LINT_VERSION}-linux-amd64.tar.gz
          tar -xzf ./golangci-lint.tar.gz
          cp ./golangci-lint-${GOLANGCI_LINT_VERSION}-linux-amd64/golangci-lint ./
        env:
          GOLANGCI_LINT_VERSION: "1.45.2"
      - name: run golangci-lint
        run: ./golangci-lint run --config test.golangci.yml ./...
  test:
    strategy:
      matrix:
        go_version:
          - 1.18.x
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go_version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go_version }}
      - name: test
        run: go test -v -race -coverprofile=cover.os-${{ matrix.os }}.ver-${{ matrix.go_version }}.txt -covermode=atomic ./...
      - name: upload coverage
        uses: codecov/codecov-action@v3
        if: ${{ matrix.go_version == '1.18.x' }}
        with:
          files: ./cover.os-${{ matrix.os }}.ver-${{ matrix.go_version }}.txt
